package ictgradschool.project;

import java.sql.*;

//just basic function, need to be modified in the future.
public class ArticleDAO {


    public static boolean insertArticle(Article article, Connection conn) throws SQLException {


        try (PreparedStatement stmt = conn.prepareStatement(
                "INSERT INTO pb_article (title, content, dateCreated, imageFileName,authorId) VALUES (?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, article.getTitle());
            stmt.setString(2, article.getContent());
            stmt.setDate(3, (Date) article.getDate());
            stmt.setInt(4,article.getAuthorID());

            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected == 0) {
                return false;
            }

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                keys.next();
                int articleID = keys.getInt(1);
                article.setArticleId(articleID); // Set the articleID to the one generated by the DB.

                return true;
            }

        }

    }

    public static boolean insertArticleWithoutDateAndImage(Article article, Connection conn) throws SQLException {


        try (PreparedStatement stmt = conn.prepareStatement(
                "INSERT INTO pb_article (title, content,authorId) VALUES (?, ?, ?)", Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, article.getTitle());
            stmt.setString(2, article.getContent());
            stmt.setInt(3,article.getAuthorID());

            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected == 0) {
                return false;
            }

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                keys.next();
                int articleID = keys.getInt(1);
                article.setArticleId(articleID);

                return true;
            }

        }

    }

}
